import type { Metadata } from "next";
import { Providers } from "../../utils/ThemeProvider";
import "../globals.css";
import HomeWrapper from "./homeWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <HomeWrapper>{children}</HomeWrapper>
    </Providers>
  );
}
